import { auth } from "@/lib/auth"
import { prisma } from "@/lib/db/prisma"
import BuyLeadButton from "@/components/features/BuyLeadButton"

export default async function HotCallsMarketplacePage() {
  const session = await auth()
  if (!session) return null

  const listings = await prisma.marketplaceListing.findMany({
    where: { status: 'ACTIVE' },
    include: { lead: true },
    orderBy: { createdAt: 'desc' }
  })

  // Filter out the user's own listings
  const availableListings = listings.filter(l => l.sellerId !== session.user.id)
  const myListings = listings.filter(l => l.sellerId === session.user.id)

  return (
    <div className="p-8 max-w-7xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Hot Call Marketplace</h1>
        <p className="text-slate-500 mt-1">Purchase highly-qualified leads generated by other users.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-4">
          <h2 className="text-lg font-semibold text-slate-900 mb-4">Available Leads</h2>
          {availableListings.map(listing => (
            <div key={listing.id} className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 flex justify-between items-center hover:shadow-md transition">
              <div>
                <div className="flex items-center space-x-3 mb-2">
                  <span className="bg-orange-100 text-orange-800 text-xs font-bold px-2.5 py-0.5 rounded uppercase tracking-wide">
                    {listing.lead.industry || 'Unknown Industry'}
                  </span>
                  <span className="text-sm font-medium text-slate-500">
                    📍 {listing.lead.city || 'Unknown Location'}
                  </span>
                </div>
                <h3 className="text-xl font-bold text-slate-900 blur-sm select-none" title="Company name hidden until purchased">
                  {listing.lead.companyName}
                </h3>
                <p className="text-sm text-slate-500 mt-1">
                  Lead Score: <span className="font-semibold text-indigo-600">{listing.lead.leadScore}</span>
                </p>
              </div>
              <div className="text-right">
                <p className="text-2xl font-black text-slate-900 mb-2">{listing.askingPrice} <span className="text-sm font-normal text-slate-500">Credits</span></p>
                <BuyLeadButton listingId={listing.id} price={listing.askingPrice} />
              </div>
            </div>
          ))}
          {availableListings.length === 0 && (
            <div className="text-center py-20 bg-white rounded-xl border border-dashed border-slate-300">
              <h3 className="text-lg font-medium text-slate-900">No leads available</h3>
              <p className="text-slate-500 mt-2">Check back later for new hot calls.</p>
            </div>
          )}
        </div>

        <div>
          <div className="bg-slate-50 rounded-xl border border-slate-200 p-6">
            <h2 className="text-lg font-semibold text-slate-900 mb-4">My Active Listings</h2>
            <div className="space-y-4">
              {myListings.map(listing => (
                <div key={listing.id} className="bg-white rounded-lg border border-slate-200 p-4">
                  <h4 className="font-semibold text-slate-900 truncate">{listing.lead.companyName}</h4>
                  <div className="flex justify-between items-center mt-2">
                    <span className="text-sm text-slate-500">Asking: {listing.askingPrice} credits</span>
                    <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-1 rounded-full font-medium">Active</span>
                  </div>
                </div>
              ))}
              {myListings.length === 0 && (
                <p className="text-sm text-slate-500">You have no active listings. Go to a lead in your CRM to sell it.</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
